### ISSUE TITLE
Extraction Header ville de Dakar

### ISSUE THREAD

**Issue by dofbi** [senegalx/defarsamagox#1]
Isolé le code HTML et CSS du Header du site de la ville de Dakar https://villededakar.sn
![Capture d’écran du 2023-02-03 22-57-44](https://user-images.githubusercontent.com/84446/216727841-f18c2290-5eea-4864-a57b-4344a5d66406.png)

**Comment by HABIBMBALLO** [comment]
``
![WhatsApp Image 2023-02-05 at 21 24 33](https://user-images.githubusercontent.com/48298145/216954114-e996007f-fa7a-4497-af35-90a980e527c8.jpeg)

**Comment by HABIBMBALLO** [comment]
Ready

**Comment by dofbi** [comment]
Ajouter le code dans **HTML** le Header voir le fichier 
```
templates/web/defarsamagox/header.html
```
> [% INCLUDE 'header_villededakar.html' %]

Ajouter le code **CSS** dans

```
web/cobrands/defarsamagox/layout.scss
```

**Comment by HABIBMBALLO** [comment]
`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com"> 
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
    <link href="https://fonts.googleapis.com/css2?family=Cabin&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Header - Ville de Dakar</title>
    <script src="https://kit.fontawesome.com/5786bcee1e.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <div class="logo">
            <img src="https://villededakar.sn/wp-content/uploads/2020/12/logo-ville-H.png" alt="Ville de Dakar" class="desk-logo d-none d-lg-block d-xl-block" style="width:200px ; height:auto" />
        </div>
        <nav>
            <ul>
                <li class="seach"><i class="fa-sharp fa-solid fa-magnifying-glass"></i></li>
                <li><a href="#">Accueil</a></li>
                <li><a href="#">Actualité</a></li>
                <li><a href="#">Découvrir Dakar</a></li>
                <li><a href="#">La mairie</a></li>
                <li><a href="#">E-Services</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>    
    </header>  
</body>
</html>
`

`
header {
    display: flex;
    justify-content: space-between;
    padding: 20px;
}

header nav ul {
    display: flex;
    padding: 0px 120px;
    list-style-type: none;
    margin: 0;
}

header nav ul li {
    padding: 10px 5px;
    margin: 0px 20px 0px 20px;
}

header nav ul li a {
    font-family:"Cabin", Sans-serif;
    font-size:17px;
    font-weight:400;
    color: #202B5D;
    text-decoration: none;
}

header nav ul li:hover a {
    color: #FF3514;
}
.seach {
    font-size:14px;
    font-size: 20px;
    color: #202B5D;
    margin: 0px 0px 0px 20px;
}
`

**Comment by HABIBMBALLO** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com"> 
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
    <link href="https://fonts.googleapis.com/css2?family=Cabin&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Header - Ville de Dakar</title>
    <script src="https://kit.fontawesome.com/5786bcee1e.js" crossorigin="anonymous"></script>
</head>
<body>

    <header>

        <div class="logo">
            <img src="https://villededakar.sn/wp-content/uploads/2020/12/logo-ville-H.png" alt="Ville de Dakar" class="desk-logo d-none d-lg-block d-xl-block" style="width:200px ; height:auto" />
        </div>

        <nav>
            <ul>
                <li class="seach"><i class="fa-sharp fa-solid fa-magnifying-glass"></i></li>
                <li><a href="#">Accueil</a></li>
                <li><a href="#">Actualité</a></li>
                <li><a href="#">Découvrir Dakar</a></li>
                <li><a href="#">La mairie</a></li>
                <li><a href="#">E-Services</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
        
    </header>
     
</body>
</html>

**Comment by dofbi** [comment]
Hello @HABIBMBALLO 
voici
![defar-haut](https://user-images.githubusercontent.com/84446/217684347-1648b0cc-c821-474a-a0ba-a7ac3c890904.png)
